// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using site.Data;

#nullable disable

namespace site.Migrations
{
    [DbContext(typeof(MVCMagazinDbContext))]
    [Migration("20230426223419_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("site.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("site.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("site.Models.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identificator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Poost")
                        .HasColumnType("int");

                    b.Property<string>("TittlePost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("site.Models.Domain.Sklad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberSklad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sklad");
                });

            modelBuilder.Entity("site.Models.Domain.Tovar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tovar");
                });

            modelBuilder.Entity("site.Models.Domain.Zakaz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SkladId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TovarId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkladId");

                    b.HasIndex("TovarId");

                    b.ToTable("Zakaz");
                });

            modelBuilder.Entity("site.Models.Domain.Employee", b =>
                {
                    b.HasOne("site.Models.Domain.Post", "Post")
                        .WithMany("Employee")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("site.Models.Domain.Zakaz", b =>
                {
                    b.HasOne("site.Models.Domain.Client", "Client")
                        .WithMany("Zakaz")
                        .HasForeignKey("ClientID");

                    b.HasOne("site.Models.Domain.Employee", "Employee")
                        .WithMany("Zakaz")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("site.Models.Domain.Sklad", "Sklad")
                        .WithMany("Zakaz")
                        .HasForeignKey("SkladId");

                    b.HasOne("site.Models.Domain.Tovar", "Tovar")
                        .WithMany("Zakaz")
                        .HasForeignKey("TovarId");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Sklad");

                    b.Navigation("Tovar");
                });

            modelBuilder.Entity("site.Models.Domain.Client", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("site.Models.Domain.Employee", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("site.Models.Domain.Post", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("site.Models.Domain.Sklad", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("site.Models.Domain.Tovar", b =>
                {
                    b.Navigation("Zakaz");
                });
#pragma warning restore 612, 618
        }
    }
}
